swagger: '2.0'
info:
  version: 0.5.2
  title: Citoid
  description: A citation service relying on Zotero
  termsOfService: https://wikimediafoundation.org/wiki/Terms_of_Use
  contact:
    name: the Wikimedia Services team
    url: http://mediawiki.org/wiki/Services
  license:
    name: Apache2
    url: http://www.apache.org/licenses/LICENSE-2.0
paths:
  # from routes/root.js
  /robots.txt:
    get:
      tags:
        - Root
        - Robots
      description: Gets robots.txt
      x-monitor: false
  /:
    get:
      tags:
        - Root
      description: The root service end-point
      produces:
        - application/json
      x-amples:
        - title: spec from root
          request:
            query:
              spec: true
          response:
            status: 200
  # from routes/info.js
  /_info:
    get:
      tags:
        - Service information
      description: Gets information about the service
      produces:
        - application/json
      x-amples:
        - title: retrieve service info
          request: {}
          response:
            status: 200
            headers:
              content-type: application/json
            body:
              name: /.+/
              description: /.+/
              version: /.+/
              home: /.+/
  # from routes/citoid.js
  /api:
    get:
      tags:
        - Citations
      description: Converts URLs, DOIs, ISBNs, PMIDs, etc into citations
      produces:
        - application/json; charset=utf-8;
        - application/x-bibtex; charset=utf-8
      parameters:
        - name: format
          in: query
          description: "The format to use for the resulting citation data"
          type: string
          enum:
            - mediawiki
            - mediawiki-basefields
            - zotero
            - bibtex
          required: true
        - name: search
          in: query
          description: >
            URL of an article, DOI, ISBN, PMCID or PMID in the URL-encoded format.
            Note that on the Swagger-UI doc page you don't need to URI-encode the
            parameter manually, it will be done by the docs engine.
          schema:
            type: string
          required: true
        - name: Accept-Language
          in: header
          type: string
          required: false
          description: >
            Provides citation metadata in the requested language, if it is available.
      x-amples:
        - title: bad URL
          request:
            query:
              format: mediawiki
              search: http://example.com/thisurldoesntexist
            headers:
              accept-language: en
          response:
            status: 404
        - title: Zotero alive
          request:
            query:
              format: bibtex
              search: http://example.com
            headers:
              accept-language: en
          response:
            status: 200
        - title: Scrapes sample page
          request:
            query:
              format: mediawiki
              search: http://example.com
            headers:
              accept-language: en
          response:
            status: 200
            body:
              - itemType: /.+/
                title: /.+/
                url: /.+/
                accessDate: /.+/
      responses:
        '200':
          description: The citation data in the requested format
          schema:
            required:
              - title
              - url
              - itemType
            properties:
              itemType:
                type: string
              title:
                type: string
              url:
                type: string
        '404':
          description: Citation data was not found.
          schema:
            required:
              - Error
            properties:
              Error:
                type: string
